//please dont hate on me
//i was against this, but now im too lazy to do anything about it
#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <string>
#include <math.h>
#include <cstdlib>
#include <vector>
#include <unordered_map>
#include <numbers>
#include <cassert>
#include <filesystem>
#include <memory>
#include <array>
#include <numeric>
#include <string_view>
#include <unordered_set>
#include <functional>
#include <iostream>//only used for debugging can be removed
#include <stdexcept>
#include <fstream>
#include <typeinfo> // for typeid
#include <sstream>
#include <random>
#include <algorithm>
#include <cstdint>
#include <cstring>
#include <execution>
#include <thread>
#include <future>
#include <mutex>
#include <atomic>
#include <condition_variable>
#include "ObjectFactory.hpp"
#include "Camera.hpp"
#include "Object.hpp"
#include "sprite.hpp"
#include "CollisionDetector.hpp"
#include "Terrain.hpp"
#include "EditorMap.hpp"
#include "GameMap.hpp"
#include "CutScene.hpp"
#include "Animation.hpp"
#include "HappyEnd.hpp"
#include "bloodParticles.hpp"
#include "bloodParticle.hpp"
#include "laserEnd.hpp"
#include "TextBox.hpp"
#include "idk.hpp"
#include "attack.hpp"
#include "Boss.hpp"
#include "PacMan.hpp"
#include "hedgehog.hpp"
#include "player.hpp"
#include "npc.hpp"
#include "npcs.hpp"
#include "staticObjects.hpp"
#include "SpawnPoint.hpp"
#include "penguin.hpp"
#include "ak47.hpp"
#include "Menu.hpp"
#include "GameOverScreen.hpp"
#include "item.hpp"
#include "inventory.hpp"
#include "leveleditor.hpp"
#include "Background.hpp"