#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <string>
#include <math.h>
#include <cstdlib>
#include <vector>
#include <unordered_map>
#include <numbers>
#include <cassert>
#include <filesystem>
#include <memory>
#include <array>
#include <numeric>
#include <string_view>
#include <functional>
#include <iostream>//only used for debugging can be removed
#include <stdexcept>
#include <fstream>
#include <sstream>
#include <random>
#include <algorithm>
#include <cstdint>
#include <cstring>
#include <execution>
#include <thread>
#include <future>
#include <mutex>
#include <atomic>
#include <condition_variable>
#include "GifPlayer.hpp"
#include "EntityFactory.hpp"
#include "Entity.hpp"
#include "EditorMap.hpp"
#include "GameMap.hpp"
#include "CutScene.hpp"
#include "sprite.hpp"
#include "Animation.hpp"
#include "CollisionDetector.hpp"
#include "TextBox.hpp"
#include "idk.hpp"
#include "attack.hpp"
#include "Boss.hpp"
#include "PacMan.hpp"
#include "player.hpp"
#include "npc.hpp"
#include "penguin.hpp"
#include "Menu.hpp"
#include "GameOverScreen.hpp"
#include "item.hpp"
#include "inventory.hpp"